services:
  db:
    image: mysql:8.0
    container_name: joomla_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: joomla_db
      MYSQL_USER: joomla_user
      MYSQL_PASSWORD: joomla_password
    volumes:
      - db_data:/var/lib/mysql

  joomla:
    image: joomla:latest
    container_name: joomla_site
    restart: always
    ports:
      - "8082:80"
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: joomla_user
      JOOMLA_DB_PASSWORD: joomla_password
      JOOMLA_DB_NAME: joomla_db
    depends_on:
      - db

  mcp-server:
    build: ./mcp-server
    container_name: joomla_mcp
    restart: always
    ports:
      - "6274:6274"
    environment:
      DB_HOST: db
      DB_USER: joomla_user
      DB_PASSWORD: joomla_password
      DB_NAME: joomla_db
      DB_PREFIX: "joos_"
      JOOMLA_API_TOKEN: "${JOOMLA_API_TOKEN}" # Preso dal file .env
      JOOMLA_API_BASE: "http://joomla/api/index.php/v1" # Host interno Docker
    volumes:
      - ./joomla_html:/var/www/html # Permette all'IA di leggere/scrivere file
    depends_on:
      - db
    stdin_open: true
    ## tty: true

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: joomla_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: joomla_user
      PMA_PASSWORD: joomla_password
    depends_on:
      - db

volumes:
  db_data:
